id: A5A5F4B4A
title: Prayer to Gatön Ngawang Lekpa
type: translation
pechas:
- I9C97A1EA
- I675DDF0D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:56:39.856277
  last_modified_at: 2023-01-04 11:56:39.856284
  collections:
  - Gatön Ngawang Lekpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I9C97A1EA/527F: DA9D
  I675DDF0D/2730: DA9D
